export const listRooms=[
  {
      "deleteAt": false,
      "_id": "6165513adc423b001dd9c044",
      "name": "Saigon Emerald Resort",
      "guests": 2,
      "bedRoom": 2,
      "bath": 3,
      "description": "Khách Sạn này thật tuyệt vời",
      "price": 100000,
      "elevator": false,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": false,
      "dryer": true,
      "gym": false,
      "kitchen": true,
      "wifi": true,
      "heating": true,
      "cableTV": true,
      "locationId": {
          "deleteAt": false,
          "name": "Thành phố Đà Nẵng",
          "province": "Đà Nẵng",
          "country": "Việt Nam",
          "valueate": 8,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1651290776928_shutterstock-1169930359-4299-1593590420.jpg"
      },
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1653067766301_764854.png"
  },
  {
      "deleteAt": false,
      "_id": "61655587dc423b001dd9c04a",
      "name": "Khách Sạn Hồng Hào",
      "guests": 2,
      "bedRoom": 0,
      "bath": 5,
      "description": "Khách Sạn đẹp quá đi thôi",
      "price": 20000000,
      "elevator": true,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": true,
      "dryer": true,
      "gym": true,
      "kitchen": true,
      "wifi": true,
      "heating": true,
      "cableTV": false,
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1658417402740_hotel-room-design-trends-italianbark-interior-design-blog.jpg",
      "locationId": {
          "deleteAt": false,
          "name": "Chùa Cầu Hội An",
          "province": "Hội An",
          "country": "Việt Nam",
          "valueate": 10,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1656459879803_chua-cau-1.jpg"
      }
  },
  {
      "deleteAt": false,
      "_id": "616555d3dc423b001dd9c053",
      "name": "Phòng Siêu Vip Pro",
      "guests": 5,
      "bedRoom": 2,
      "bath": 3,
      "description": "Khách Sạn này thật tuyệt vời",
      "price": 100000,
      "elevator": true,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": false,
      "dryer": false,
      "gym": false,
      "kitchen": true,
      "wifi": true,
      "heating": true,
      "cableTV": true,
      "locationId": {
          "deleteAt": false,
          "name": "Khu phố tây Trần Phú",
          "province": "Nha Trang, Khánh Hoà",
          "country": "Việt Nam",
          "valueate": 7,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1656432692952_5e984d8059d27.jpg"
      },
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1654708437172_dirtiest-1170x650.jpg"
  },
  {
      "deleteAt": false,
      "_id": "616596b9dc423b001dd9c06e",
      "name": "Khách Sạn Palace",
      "guests": 8,
      "bedRoom": 5,
      "bath": 5,
      "description": "Khách sạn Palace là một khách sạn 4 sao đầu tiên của Vũng Tàu, tọa lạc ngay tại trung tâm thành phố, rất thuận tiện cho du khách đi thăm quan các điểm du lịch, giải trí, mua sắm. Đặc biệt Khách sạn Palace tự hào là sự lựa chọn tin cậy để tổ chức các sự kiện quan trọng của Tỉnh, các hội nghị quốc tế, là nơi tiếp đón các đoàn khách ngoại giao, và các nguyên thủ quốc gia Khách sạn Palace Vũng tàu bao gồm 95 phòng ngủ và 17 căn hộ cao cấp đầy đủ tiện nghi, là trung tâm hội nghị quốc tế và hiện đại nhất tại Vũng Tàu, khu vực nhà hàng và phòng tiệc có khả năng phục vụ cùng lúc lên tới 1.000 khách.  Câu lạc bộ Palace Gamming & Bar nằm trong khuôn viên khách sạn cung cấp dịch vụ trò chơi có thưởng cho các du khách là người nước ngoài và Việt kiều. Với hệ thống máy được trang bị hiện đại tạo cho khách hàng sẽ có cảm giác thư giãn và thích thú  Tại khách sạn Palace với hệ thống dịch vụ hoàn chỉnh, phong cách phục vụ chuyên nghiệp cùng sự thân thiện của đội ngũ nhân viên khách sạn, chúng tôi cam kết sẽ đem đến sự hài lòng cho Quý Khách",
      "price": 690000,
      "elevator": true,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": false,
      "dryer": false,
      "gym": false,
      "kitchen": true,
      "wifi": true,
      "heating": true,
      "cableTV": true,
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1658417426651_dirtiest-1170x650.jpg",
      "locationId": {
          "deleteAt": false,
          "name": "Chùa Cầu Hội An",
          "province": "Hội An",
          "country": "Việt Nam",
          "valueate": 10,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1656459879803_chua-cau-1.jpg"
      }
  },
  {
      "deleteAt": false,
      "_id": "6166562edc423b001dd9c0cf",
      "name": "Khách Sạn Cap Saint Jacques",
      "guests": 2,
      "bedRoom": 2,
      "bath": 3,
      "description": " Khách sạn Cap Saint Jacques là khách sạn bốn sao nổi tiếng tại Vũng Tàu, nằm ở vị trí đẹp ở Bãi Sau, chỉ cách 200 mét từ sân golf Paradise và năm phút từ trung tâm thành phố Vũng Tàu, rất thuận tiện đi đến các địa điểm chính. Khách sạn có các loại phòng sang trọng và đầy đủ tiện nghi đạt chuẩn bốn sao như két an tòan, truyền hình vệ tinh, Internet WIFI. Đối với khách là doanh nhân thì có phòng hội nghị với thiết bị như máy chiếu, hệ thống loa và màn hình. Nhà hàng của khách sạn phục vụ các món ăn Việt Nam phong phú chế biến từ hải sản. Ngòai ra, những du khách tìm kiếm sự thư giãn qua vận động thể thao có thể sử dụng các tiện ích như sân tennis, hồ bơi và phòng tập thể dục. Khách sạn Cap Saint Jacques đúng là sự lựa chọn phù hợp cho những du khách đang tìm kiếm một nơi yên tĩnh vào cuối ngày. ",
      "price": 1050000,
      "elevator": true,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": false,
      "dryer": true,
      "gym": false,
      "kitchen": false,
      "wifi": true,
      "heating": true,
      "cableTV": true,
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1657798248527_images.jpg",
      "locationId": {
          "deleteAt": false,
          "name": "Khu du lịch Suối Mơ",
          "province": "Vũng Tàu",
          "country": "Việt Nam",
          "valueate": 9,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1656528784835_suoi-mo-park1.jpg"
      }
  },
  {
      "deleteAt": false,
      "_id": "61665651dc423b001dd9c0d1",
      "name": "khách sạn bluesea",
      "guests": 3,
      "bedRoom": 3,
      "bath": 3,
      "description": "Khách Sạn này thật tuyệt vời",
      "price": 150000,
      "elevator": false,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": false,
      "dryer": true,
      "gym": false,
      "kitchen": true,
      "wifi": true,
      "heating": true,
      "cableTV": true,
      "locationId": {
          "deleteAt": false,
          "name": "Vịnh Vĩnh Hy",
          "province": "Ninh Thuận",
          "country": "Việt Nam",
          "valueate": 10,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1636702668612_ninhthuan.jpg"
      },
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1649756477236_Screenshot from 2022-04-05 23-32-06.png"
  },
  {
      "deleteAt": false,
      "_id": "61698b62efe193001c0a5ba3",
      "name": "Nha Trang Panorama",
      "guests": 4,
      "bedRoom": 2,
      "bath": 2,
      "description": "Trên cả tuyệt vời",
      "price": 500000,
      "elevator": true,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": true,
      "dryer": false,
      "gym": false,
      "kitchen": true,
      "wifi": true,
      "heating": true,
      "cableTV": true,
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1640942937727_giay dan tuong co dan duoc len gach khong.jpg",
      "locationId": {
          "deleteAt": false,
          "name": "Vịnh Vĩnh Hy",
          "province": "Ninh Thuận",
          "country": "Việt Nam",
          "valueate": 10,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1636702668612_ninhthuan.jpg"
      }
  },
  {
      "deleteAt": false,
      "_id": "61698c1eefe193001c0a5ba8",
      "name": "Nha Trang Galina Hotel",
      "guests": 5,
      "bedRoom": 3,
      "bath": 4,
      "description": "Dịch vụ like shit",
      "price": 850000,
      "elevator": false,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": true,
      "dryer": false,
      "gym": true,
      "kitchen": true,
      "wifi": true,
      "heating": true,
      "cableTV": true,
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1658146724696_put-together-a-perfect-guest-room-1976987-hero-223e3e8f697e4b13b62ad4fe898d492d.jpg",
      "locationId": {
          "deleteAt": false,
          "name": "Động Phong Nha",
          "province": "Quảng Bình",
          "country": "Việt Nam",
          "valueate": 9,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1656460707859_9.jpg"
      }
  },
  {
      "deleteAt": false,
      "_id": "61698c5fefe193001c0a5baa",
      "name": "Nha Trang Cẩm Tiên Hotel",
      "guests": 3,
      "bedRoom": 3,
      "bath": 3,
      "description": "Phòng hơi nhỏ, không khí tốt lắm 10 điểm",
      "price": 300000,
      "elevator": false,
      "hotTub": false,
      "pool": false,
      "indoorFireplace": false,
      "dryer": false,
      "gym": false,
      "kitchen": false,
      "wifi": true,
      "heating": false,
      "cableTV": true,
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1634308467196_camtienhotel.jpg",
      "locationId": {
          "deleteAt": false,
          "name": "Chùa Cầu Hội An",
          "province": "Hội An",
          "country": "Việt Nam",
          "valueate": 10,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1656459879803_chua-cau-1.jpg"
      }
  },
  {
      "deleteAt": false,
      "_id": "61698d46efe193001c0a5bb2",
      "name": "InterContinental Nha Trang ",
      "guests": 2,
      "bedRoom": 2,
      "bath": 1,
      "description": "My stay was simply outstanding on all levels. The hotel staff were professional, friendly and efficient.",
      "price": 800000,
      "elevator": true,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": true,
      "dryer": true,
      "gym": true,
      "kitchen": true,
      "wifi": true,
      "heating": false,
      "cableTV": true,
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1658151650876_Barbie-Room_You-Can-Be-Anything-1-scaled-ph8xeffw7ize2u2735bjhogk9skanmascopumcteyo.jpg",
      "locationId": {
          "deleteAt": false,
          "name": "Vịnh Vĩnh Hy",
          "province": "Ninh Thuận",
          "country": "Việt Nam",
          "valueate": 10,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1636702668612_ninhthuan.jpg"
      }
  },
  {
      "deleteAt": false,
      "_id": "61698d73efe193001c0a5bb4",
      "name": "Sheraton Nha Trang Hotel & Spa",
      "guests": 5,
      "bedRoom": 2,
      "bath": 2,
      "description": "Great views from room.  What a view!  Room was cozy and easy to use everything. I stayed two days here, but I wanted to stay more.  Easy access to beach.  Hotel has great pool but crowded for most of time.  Lobby was nice and you could feel a wind of southeast Asia at the very first.",
      "price": 900000,
      "elevator": true,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": true,
      "dryer": true,
      "gym": true,
      "kitchen": true,
      "wifi": true,
      "heating": false,
      "cableTV": true,
      "locationId": {
          "deleteAt": false,
          "name": "Vịnh Vĩnh Hy",
          "province": "Ninh Thuận",
          "country": "Việt Nam",
          "valueate": 10,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1636702668612_ninhthuan.jpg"
      },
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1656690770842_download (1).jpg"
  },
  {
      "deleteAt": false,
      "_id": "61698f8befe193001c0a5bba",
      "name": "Khách sạn Nagar Nha Trang",
      "guests": 5,
      "bedRoom": 2,
      "bath": 2,
      "description": "Đồ ăn buffet ngon",
      "price": 700000,
      "elevator": true,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": true,
      "dryer": true,
      "gym": true,
      "kitchen": true,
      "wifi": true,
      "heating": true,
      "cableTV": true,
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1658146594396_put-together-a-perfect-guest-room-1976987-hero-223e3e8f697e4b13b62ad4fe898d492d.jpg",
      "locationId": {
          "deleteAt": false,
          "name": "Vịnh Vĩnh Hy",
          "province": "Ninh Thuận",
          "country": "Việt Nam",
          "valueate": 10,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1636702668612_ninhthuan.jpg"
      }
  },
  {
      "deleteAt": false,
      "_id": "616996acefe193001c0a5bdc",
      "name": "Khách Sạn Metropole",
      "guests": 6,
      "bedRoom": 3,
      "bath": 2,
      "description": "Phong cách rất sang chảnh",
      "price": 1000000,
      "elevator": true,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": true,
      "dryer": true,
      "gym": true,
      "kitchen": false,
      "wifi": true,
      "heating": true,
      "cableTV": true,
      "locationId": {
          "deleteAt": false,
          "province": "Kiên Giang",
          "country": "Việt Nam",
          "valueate": 8,
          "name": "Đảo Nam Du",
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1636858118366_nam_du_islands.jpg"
      },
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1635429164629_kha-hostel-cafe.jpg"
  },
  {
      "deleteAt": false,
      "_id": "616996d4efe193001c0a5bde",
      "name": "Gemini Saigon Hotel",
      "guests": 2,
      "bedRoom": 1,
      "bath": 1,
      "description": "Phòng nhỏ xinh rất ưng ý",
      "price": 500000,
      "elevator": true,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": true,
      "dryer": true,
      "gym": true,
      "kitchen": false,
      "wifi": true,
      "heating": true,
      "cableTV": true,
      "locationId": {
          "deleteAt": false,
          "name": "Khu du lịch Đầm Sen",
          "province": "Thành phố Hồ Chí Minh",
          "country": "Việt Nam",
          "valueate": 8,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1656460226996_1.jpg"
      },
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1634310281730_geminisaigon.jpg"
  },
  {
      "deleteAt": false,
      "_id": "6169970eefe193001c0a5be3",
      "name": "New World Hotel",
      "guests": 2,
      "bedRoom": 2,
      "bath": 2,
      "description": "Great views from room.  What a view!  Room was cozy and easy to use everything. I stayed two days here, but I wanted to stay more.  Easy access to beach.  Hotel has great pool but crowded for most of time.  Lobby was nice and you could feel a wind of southeast Asia at the very first.",
      "price": 900000,
      "elevator": true,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": true,
      "dryer": true,
      "gym": true,
      "kitchen": true,
      "wifi": true,
      "heating": false,
      "cableTV": true,
      "locationId": {
          "deleteAt": false,
          "name": "Vịnh Vĩnh Hy",
          "province": "Ninh Thuận",
          "country": "Việt Nam",
          "valueate": 10,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1636702668612_ninhthuan.jpg"
      },
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1634310414778_lahotelsaigon.jpg"
  },
  {
      "deleteAt": false,
      "_id": "6169973eefe193001c0a5be7",
      "name": "Vien Dong Hotel",
      "guests": 3,
      "bedRoom": 2,
      "bath": 1,
      "description": "chất lượng dịch vụ rất ok",
      "price": 800000,
      "elevator": true,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": true,
      "dryer": true,
      "gym": true,
      "kitchen": false,
      "wifi": true,
      "heating": true,
      "cableTV": true,
      "locationId": {
          "deleteAt": false,
          "name": "Vịnh Vĩnh Hy",
          "province": "Ninh Thuận",
          "country": "Việt Nam",
          "valueate": 10,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1636702668612_ninhthuan.jpg"
      },
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1634310452881_viendongsaigon.jpg"
  },
  {
      "deleteAt": false,
      "_id": "61699769efe193001c0a5be9",
      "name": "hotel Đại Nam",
      "guests": 2,
      "bedRoom": 2,
      "bath": 2,
      "description": "Great views from room.  What a view!  Room was cozy and easy to use everything. I stayed two days here, but I wanted to stay more.  Easy access to beach.  Hotel has great pool but crowded for most of time.  Lobby was nice and you could feel a wind of southeast Asia at the very first.",
      "price": 900000,
      "elevator": true,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": true,
      "dryer": true,
      "gym": true,
      "kitchen": true,
      "wifi": true,
      "heating": false,
      "cableTV": true,
      "locationId": {
          "deleteAt": false,
          "name": "Vịnh Vĩnh Hy",
          "province": "Ninh Thuận",
          "country": "Việt Nam",
          "valueate": 10,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1636702668612_ninhthuan.jpg"
      },
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1634310490236_phanlanhotel.jpg"
  },
  {
      "deleteAt": false,
      "_id": "616997a2efe193001c0a5bee",
      "name": "Saigon 1979 Hotel",
      "guests": 1,
      "bedRoom": 1,
      "bath": 1,
      "description": "Phong cách sài gòn cổ khá hay",
      "price": 300000,
      "elevator": true,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": false,
      "dryer": true,
      "gym": true,
      "kitchen": true,
      "wifi": true,
      "heating": false,
      "cableTV": true,
      "locationId": {
          "deleteAt": false,
          "name": "Đình Sơn City",
          "province": "Hồ Chí Minh",
          "country": "Việt Nam",
          "valueate": 10,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1658152393126_landmark-81-2_1638069009.jpg"
      },
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1634310532625_saigon1979hostel.jpg"
  },
  {
      "deleteAt": false,
      "_id": "61716fd2efe193001c0a76f0",
      "name": "Chợ nổi hotel",
      "guests": 5,
      "bedRoom": 2,
      "bath": 2,
      "description": "The hotel staff are amazing, helpful and friendly.",
      "price": 400000,
      "elevator": true,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": true,
      "dryer": false,
      "gym": false,
      "kitchen": false,
      "wifi": true,
      "heating": true,
      "cableTV": true,
      "locationId": {
          "deleteAt": false,
          "name": "Chợ nổi Ngã Năm",
          "province": "Sóc Trăng",
          "country": "Việt Nam",
          "valueate": 9,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1656385665997_chonoinganam-1-1.jpg"
      },
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1658162562148_download (1).jpg"
  },
  {
      "deleteAt": false,
      "_id": "6171707fefe193001c0a76f6",
      "name": "Victoria Can Tho Resort",
      "guests": 4,
      "bedRoom": 2,
      "bath": 5,
      "description": "I have been in this hotel since 2000 yes.. about 21 years... it did not change but look same as original with the best service ever and all the small attention to the guest.. I am very impressed of this hotel and keep on liking to go back.. almost I came back to Cantho to be staying in Victoria.. in nowhere on earth I feel that..",
      "price": 900000,
      "elevator": true,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": false,
      "dryer": false,
      "gym": false,
      "kitchen": false,
      "wifi": true,
      "heating": false,
      "cableTV": true,
      "locationId": {
          "deleteAt": false,
          "name": "Vườn sinh thái Hoa Súng",
          "province": "Cần Thơ",
          "country": "Việt Nam",
          "valueate": 10,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1658162873699_Capture-213.png"
      },
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1658162736308_arbisoftimages-3008716-Hotel_CityRooms3-691309.jpg"
  },
  {
      "deleteAt": false,
      "_id": "61717339efe193001c0a7709",
      "name": "Green Bay Phu Quoc Resort & Spa",
      "guests": 5,
      "bedRoom": 2,
      "bath": 2,
      "description": "Phòng đẹp, view siêu đẹp, tư vấn và phục vụ tốt, đồ ăn rất ok. Ai thích kiểu nghỉ dưỡng, hoà mình cùng thiên nhiên nên tới đây.",
      "price": 700000,
      "elevator": true,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": true,
      "dryer": true,
      "gym": false,
      "kitchen": true,
      "wifi": true,
      "heating": true,
      "cableTV": true,
      "locationId": {
          "deleteAt": false,
          "name": "Đảo Phú Quốc",
          "province": "Phú Quốc",
          "country": "Việt Nam",
          "valueate": 10,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1658163499111_du-lich-phu-quoc-2-ngay-1-dem-1_1645345403.jpg"
      },
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1634825209163_phongngu.jpg"
  },
  {
      "deleteAt": false,
      "_id": "61717b3eefe193001c0a7738",
      "name": "Khách Sạn Mộng Sương",
      "guests": 2,
      "bedRoom": 2,
      "bath": 3,
      "description": "Khách Sạn này dở ẹt",
      "price": 100000,
      "elevator": true,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": false,
      "dryer": true,
      "gym": false,
      "kitchen": true,
      "wifi": true,
      "heating": true,
      "cableTV": true,
      "locationId": {
          "deleteAt": false,
          "name": "Biển Vũng Tàu",
          "province": "Vũng Tàu",
          "country": "Việt Nam",
          "valueate": 8,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1658163044488_vung-tau.jpg"
      },
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1634827115594_iriscantho.jpg"
  },
  {
      "deleteAt": false,
      "_id": "61717bc7efe193001c0a774e",
      "name": "Vinpearl Hotel Cần Thơ",
      "guests": 5,
      "bedRoom": 2,
      "bath": 3,
      "description": "The staff is cordial and speak English. The hotel and amenities are 5 star quality. Breakfast buffet caters to Western and Asian tastes.",
      "price": 700000,
      "elevator": true,
      "hotTub": true,
      "pool": false,
      "indoorFireplace": true,
      "dryer": true,
      "gym": true,
      "kitchen": true,
      "wifi": true,
      "heating": true,
      "cableTV": true,
      "locationId": {
          "deleteAt": false,
          "name": "Vườn sinh thái Hoa Súng",
          "province": "Cần Thơ",
          "country": "Việt Nam",
          "valueate": 10,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1658162873699_Capture-213.png"
      },
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1656975927449_tuong_phat_ba_quan_am_nui_ba_den.jpg"
  },
  {
      "deleteAt": false,
      "_id": "61717c8befe193001c0a777e",
      "name": "Nesta Hotel - Can Tho Riverside",
      "guests": 2,
      "bedRoom": 2,
      "bath": 1,
      "description": "Hotel room is at ok acceptable level. Bed is clean. Bathtub and shower are bad though water leaking everywhere from the bathtub. Look like there is no drainage pipe under it. Breakfast is included and pretty good",
      "price": 800000,
      "elevator": true,
      "hotTub": false,
      "pool": true,
      "indoorFireplace": false,
      "dryer": false,
      "gym": true,
      "kitchen": true,
      "wifi": true,
      "heating": false,
      "cableTV": false,
      "locationId": {
          "deleteAt": false,
          "name": "Vườn sinh thái Hoa Súng",
          "province": "Cần Thơ",
          "country": "Việt Nam",
          "valueate": 10,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1658162873699_Capture-213.png"
      },
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1634827454337_nestacantho.jpg"
  },
  {
      "deleteAt": false,
      "_id": "61717d2defe193001c0a77c5",
      "name": "Khách sạn Ninh Kiều Cần Thơ",
      "guests": 6,
      "bedRoom": 2,
      "bath": 2,
      "description": "Stunning view over the river. Receptionist(My) there who knew English was the most helpful to us. Excellent massage(the company its not part of the hotel).",
      "price": 500000,
      "elevator": false,
      "hotTub": false,
      "pool": true,
      "indoorFireplace": false,
      "dryer": false,
      "gym": true,
      "kitchen": false,
      "wifi": true,
      "heating": false,
      "cableTV": false,
      "locationId": {
          "deleteAt": false,
          "name": "Vườn sinh thái Hoa Súng",
          "province": "Cần Thơ",
          "country": "Việt Nam",
          "valueate": 10,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1658162873699_Capture-213.png"
      },
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1634827583144_hoangsanhatrang.jpg"
  },
  {
      "deleteAt": false,
      "_id": "61717daaefe193001c0a77ec",
      "name": "Zeus Hotel",
      "guests": 1,
      "bedRoom": 2,
      "bath": 3,
      "description": "I like materials here, modern and clean. Has essential things, services you could need.",
      "price": 300000,
      "elevator": true,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": false,
      "dryer": false,
      "gym": true,
      "kitchen": true,
      "wifi": true,
      "heating": true,
      "cableTV": false,
      "locationId": {
          "deleteAt": false,
          "name": "Đình Sơn City",
          "province": "Hồ Chí Minh",
          "country": "Việt Nam",
          "valueate": 10,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1658152393126_landmark-81-2_1638069009.jpg"
      },
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1658166599117_137382403.jpg"
  },
  {
      "deleteAt": false,
      "_id": "61717e49efe193001c0a77f3",
      "name": "Azerai Hotel",
      "guests": 4,
      "bedRoom": 2,
      "bath": 3,
      "description": "Rooms and services were excellent. My family stayed for a night and really enjoyed our whole time there. Staffs were extremely friendly and helpful with all the questions that we had.",
      "price": 700000,
      "elevator": true,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": false,
      "dryer": false,
      "gym": false,
      "kitchen": false,
      "wifi": true,
      "heating": false,
      "cableTV": false,
      "locationId": {
          "deleteAt": false,
          "name": "Đình Sơn City",
          "province": "Hồ Chí Minh",
          "country": "Việt Nam",
          "valueate": 10,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1658152393126_landmark-81-2_1638069009.jpg"
      },
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1634827885857_azeraicantho.jpg"
  },
  {
      "deleteAt": false,
      "_id": "61717f15efe193001c0a7805",
      "name": "Blanar Hotel",
      "description": "Khách Sạn ",
      "price": 100000,
      "elevator": false,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": false,
      "dryer": true,
      "gym": false,
      "kitchen": true,
      "wifi": true,
      "heating": true,
      "cableTV": true,
      "locationId": {
          "deleteAt": false,
          "name": "Đình Sơn City",
          "province": "Hồ Chí Minh",
          "country": "Việt Nam",
          "valueate": 10,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1658152393126_landmark-81-2_1638069009.jpg"
      },
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1635479626704_nagarnhatrang.jpg",
      "bath": 3,
      "bedRoom": 3,
      "guests": 3
  },
  {
      "deleteAt": false,
      "_id": "61717fa0efe193001c0a780e",
      "name": "Lotus Orb Hotel",
      "guests": 2,
      "bedRoom": 2,
      "bath": 1,
      "description": "Không gian hiện đại ấm cúng ... bánh ngon, nước chuẩn",
      "price": 800000,
      "elevator": true,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": false,
      "dryer": false,
      "gym": true,
      "kitchen": true,
      "wifi": true,
      "heating": false,
      "cableTV": false,
      "locationId": {
          "deleteAt": false,
          "name": "Đình Sơn City",
          "province": "Hồ Chí Minh",
          "country": "Việt Nam",
          "valueate": 10,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1658152393126_landmark-81-2_1638069009.jpg"
      },
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1658166647257_NYC-1096x722.jpg"
  },
  {
      "deleteAt": false,
      "_id": "617180a4efe193001c0a781c",
      "name": "EPI HOUSE ",
      "guests": 5,
      "bedRoom": 2,
      "bath": 2,
      "description": "Không gian hiện đại ấm cúng ... bánh ngon, nước chuẩn",
      "price": 900000,
      "elevator": true,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": true,
      "dryer": true,
      "gym": true,
      "kitchen": true,
      "wifi": true,
      "heating": false,
      "cableTV": false,
      "locationId": {
          "deleteAt": false,
          "name": "Đình Sơn City",
          "province": "Hồ Chí Minh",
          "country": "Việt Nam",
          "valueate": 10,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1658152393126_landmark-81-2_1638069009.jpg"
      },
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1634828498128_premierepearlvungtau.jpg"
  },
  {
      "deleteAt": false,
      "_id": "617181aaefe193001c0a7831",
      "name": " New Golden Sea Hotel ",
      "guests": 5,
      "bedRoom": 2,
      "bath": 2,
      "description": "Không gian hiện đại ấm cúng ... bánh ngon, nước chuẩn",
      "price": 500000,
      "elevator": true,
      "hotTub": true,
      "pool": true,
      "indoorFireplace": true,
      "dryer": true,
      "gym": true,
      "kitchen": true,
      "wifi": true,
      "heating": false,
      "cableTV": false,
      "locationId": {
          "deleteAt": false,
          "name": "Đình Sơn City",
          "province": "Hồ Chí Minh",
          "country": "Việt Nam",
          "valueate": 10,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1658152393126_landmark-81-2_1638069009.jpg"
      },
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1634828728702_iriscantho.jpg"
  },
  {
      "deleteAt": false,
      "_id": "617181f8efe193001c0a7839",
      "name": "Sun Lake Hotel",
      "guests": 5,
      "bedRoom": 2,
      "bath": 2,
      "description": "Hotel is located in quiet area where you should go a bit far to the beach. The room was so nice and clean. They have no car parking space, only 1 car can park on pavement in front of the hotel.",
      "price": 800000,
      "elevator": true,
      "hotTub": false,
      "pool": false,
      "indoorFireplace": true,
      "dryer": true,
      "gym": true,
      "kitchen": true,
      "wifi": true,
      "heating": true,
      "cableTV": true,
      "locationId": {
          "deleteAt": false,
          "name": "Vườn sinh thái Hoa Súng",
          "province": "Cần Thơ",
          "country": "Việt Nam",
          "valueate": 10,
          "image": "https://airbnb.cybersoft.edu.vn/public/temp/1658162873699_Capture-213.png"
      },
      "__v": 0,
      "image": "https://airbnb.cybersoft.edu.vn/public/images/room/1658162956055_hotel-presidente-4s.jpg"
  }
]